### ISSUE TITLE
wakeup failed with Uncaught (in promise) 'pv_porcupine_init' failed with status INVALID_ARGUMENT

### ISSUE THREAD

**Issue by zshnb** [samie/porcupine-web-vaadin-demo#1]
I cloned project and try run in my MacOS(m1), but failed with error Uncaught (in promise) 'pv_porcupine_init' failed with status INVALID_ARGUMENT. how can I fix this error?

**Comment by samie** [comment]
First, do you have the right key set for PICOVOICE_ACCESSKEY environment variable? You get your own one from https://console.picovoice.ai

**Comment by zshnb** [comment]
yes access key is correct, I found root cause is model's version is inconsistent with web dependency

**Comment by samie** [comment]
Ok! This i something I should be update in the sample?

**Comment by zshnb** [comment]
I have figured out the root cause is model's version is inconsistent with lib's version

**Comment by samie** [comment]
Thanks. I'm not sure if I follow, did you make your own keyword model? I've seen some problems when reloading the app multiple times, but  I tested now with this and seems to run without errors: 
```
git clone git@github.com:samie/porcupine-web-vaadin-demo.git
cd porcupine-web-vaadin-demo
PICOVOICE_ACCESSKEY=[MY_ACCESS_KEY] mvn
```

**Comment by zshnb** [comment]
> Thanks. I'm not sure if I follow, did you make your own keyword model? I've seen some problems when reloading the app multiple times, but I tested now with this and seems to run without errors:
> 
> ```
> git clone git@github.com:samie/porcupine-web-vaadin-demo.git
> cd porcupine-web-vaadin-demo
> PICOVOICE_ACCESSKEY=[MY_ACCESS_KEY] mvn
> ```

no it's work with demo repo, I just want to tell you this may cause bug, so you can tip other user in docs

**Comment by samie** [comment]
Thank you! I'l close the issue.
